version: '3.8'

services:
  web:
    build: .
    container_name: php-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: datav1

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: datav1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./127_0_0_1.sql:/docker-entrypoint-initdb.d/127_0_0_1.sql

volumes:
  db_data:
